java_import(
    name = "connect",
    jars = [],
    neverlink = True,
    visibility = ["//connect:__subpackages__"],
    exports = [
        "@maven//:org_apache_kafka_connect_api",
        "@maven//:org_apache_kafka_kafka_clients",
    ],
)
